/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fourtwosix.codahale.metrics.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class HealthCheckResult implements org.apache.thrift.TBase<HealthCheckResult, HealthCheckResult._Fields>, java.io.Serializable, Cloneable, Comparable<HealthCheckResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("HealthCheckResult");

  private static final org.apache.thrift.protocol.TField HEALTHY_FIELD_DESC = new org.apache.thrift.protocol.TField("healthy", org.apache.thrift.protocol.TType.BOOL, (short)1);
  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("message", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("error", org.apache.thrift.protocol.TType.LIST, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new HealthCheckResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new HealthCheckResultTupleSchemeFactory());
  }

  public boolean healthy; // required
  public String message; // optional
  public List<HealthCheckResultError> error; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    HEALTHY((short)1, "healthy"),
    MESSAGE((short)2, "message"),
    ERROR((short)3, "error");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // HEALTHY
          return HEALTHY;
        case 2: // MESSAGE
          return MESSAGE;
        case 3: // ERROR
          return ERROR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __HEALTHY_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.MESSAGE,_Fields.ERROR};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.HEALTHY, new org.apache.thrift.meta_data.FieldMetaData("healthy", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("message", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ERROR, new org.apache.thrift.meta_data.FieldMetaData("error", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, HealthCheckResultError.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(HealthCheckResult.class, metaDataMap);
  }

  public HealthCheckResult() {
  }

  public HealthCheckResult(
    boolean healthy)
  {
    this();
    this.healthy = healthy;
    setHealthyIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public HealthCheckResult(HealthCheckResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.healthy = other.healthy;
    if (other.isSetMessage()) {
      this.message = other.message;
    }
    if (other.isSetError()) {
      List<HealthCheckResultError> __this__error = new ArrayList<HealthCheckResultError>(other.error.size());
      for (HealthCheckResultError other_element : other.error) {
        __this__error.add(new HealthCheckResultError(other_element));
      }
      this.error = __this__error;
    }
  }

  public HealthCheckResult deepCopy() {
    return new HealthCheckResult(this);
  }

  @Override
  public void clear() {
    setHealthyIsSet(false);
    this.healthy = false;
    this.message = null;
    this.error = null;
  }

  public boolean isHealthy() {
    return this.healthy;
  }

  public HealthCheckResult setHealthy(boolean healthy) {
    this.healthy = healthy;
    setHealthyIsSet(true);
    return this;
  }

  public void unsetHealthy() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __HEALTHY_ISSET_ID);
  }

  /** Returns true if field healthy is set (has been assigned a value) and false otherwise */
  public boolean isSetHealthy() {
    return EncodingUtils.testBit(__isset_bitfield, __HEALTHY_ISSET_ID);
  }

  public void setHealthyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __HEALTHY_ISSET_ID, value);
  }

  public String getMessage() {
    return this.message;
  }

  public HealthCheckResult setMessage(String message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  /** Returns true if field message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  public int getErrorSize() {
    return (this.error == null) ? 0 : this.error.size();
  }

  public java.util.Iterator<HealthCheckResultError> getErrorIterator() {
    return (this.error == null) ? null : this.error.iterator();
  }

  public void addToError(HealthCheckResultError elem) {
    if (this.error == null) {
      this.error = new ArrayList<HealthCheckResultError>();
    }
    this.error.add(elem);
  }

  public List<HealthCheckResultError> getError() {
    return this.error;
  }

  public HealthCheckResult setError(List<HealthCheckResultError> error) {
    this.error = error;
    return this;
  }

  public void unsetError() {
    this.error = null;
  }

  /** Returns true if field error is set (has been assigned a value) and false otherwise */
  public boolean isSetError() {
    return this.error != null;
  }

  public void setErrorIsSet(boolean value) {
    if (!value) {
      this.error = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case HEALTHY:
      if (value == null) {
        unsetHealthy();
      } else {
        setHealthy((Boolean)value);
      }
      break;

    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((String)value);
      }
      break;

    case ERROR:
      if (value == null) {
        unsetError();
      } else {
        setError((List<HealthCheckResultError>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case HEALTHY:
      return Boolean.valueOf(isHealthy());

    case MESSAGE:
      return getMessage();

    case ERROR:
      return getError();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case HEALTHY:
      return isSetHealthy();
    case MESSAGE:
      return isSetMessage();
    case ERROR:
      return isSetError();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof HealthCheckResult)
      return this.equals((HealthCheckResult)that);
    return false;
  }

  public boolean equals(HealthCheckResult that) {
    if (that == null)
      return false;

    boolean this_present_healthy = true;
    boolean that_present_healthy = true;
    if (this_present_healthy || that_present_healthy) {
      if (!(this_present_healthy && that_present_healthy))
        return false;
      if (this.healthy != that.healthy)
        return false;
    }

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!this.message.equals(that.message))
        return false;
    }

    boolean this_present_error = true && this.isSetError();
    boolean that_present_error = true && that.isSetError();
    if (this_present_error || that_present_error) {
      if (!(this_present_error && that_present_error))
        return false;
      if (!this.error.equals(that.error))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(HealthCheckResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetHealthy()).compareTo(other.isSetHealthy());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHealthy()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.healthy, other.healthy);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMessage()).compareTo(other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.message, other.message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetError()).compareTo(other.isSetError());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetError()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.error, other.error);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("HealthCheckResult(");
    boolean first = true;

    sb.append("healthy:");
    sb.append(this.healthy);
    first = false;
    if (isSetMessage()) {
      if (!first) sb.append(", ");
      sb.append("message:");
      if (this.message == null) {
        sb.append("null");
      } else {
        sb.append(this.message);
      }
      first = false;
    }
    if (isSetError()) {
      if (!first) sb.append(", ");
      sb.append("error:");
      if (this.error == null) {
        sb.append("null");
      } else {
        sb.append(this.error);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'healthy' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class HealthCheckResultStandardSchemeFactory implements SchemeFactory {
    public HealthCheckResultStandardScheme getScheme() {
      return new HealthCheckResultStandardScheme();
    }
  }

  private static class HealthCheckResultStandardScheme extends StandardScheme<HealthCheckResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, HealthCheckResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // HEALTHY
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.healthy = iprot.readBool();
              struct.setHealthyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ERROR
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.error = new ArrayList<HealthCheckResultError>(_list8.size);
                for (int _i9 = 0; _i9 < _list8.size; ++_i9)
                {
                  HealthCheckResultError _elem10;
                  _elem10 = new HealthCheckResultError();
                  _elem10.read(iprot);
                  struct.error.add(_elem10);
                }
                iprot.readListEnd();
              }
              struct.setErrorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetHealthy()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'healthy' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, HealthCheckResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(HEALTHY_FIELD_DESC);
      oprot.writeBool(struct.healthy);
      oprot.writeFieldEnd();
      if (struct.message != null) {
        if (struct.isSetMessage()) {
          oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
          oprot.writeString(struct.message);
          oprot.writeFieldEnd();
        }
      }
      if (struct.error != null) {
        if (struct.isSetError()) {
          oprot.writeFieldBegin(ERROR_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.error.size()));
            for (HealthCheckResultError _iter11 : struct.error)
            {
              _iter11.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class HealthCheckResultTupleSchemeFactory implements SchemeFactory {
    public HealthCheckResultTupleScheme getScheme() {
      return new HealthCheckResultTupleScheme();
    }
  }

  private static class HealthCheckResultTupleScheme extends TupleScheme<HealthCheckResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, HealthCheckResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeBool(struct.healthy);
      BitSet optionals = new BitSet();
      if (struct.isSetMessage()) {
        optionals.set(0);
      }
      if (struct.isSetError()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMessage()) {
        oprot.writeString(struct.message);
      }
      if (struct.isSetError()) {
        {
          oprot.writeI32(struct.error.size());
          for (HealthCheckResultError _iter12 : struct.error)
          {
            _iter12.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, HealthCheckResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.healthy = iprot.readBool();
      struct.setHealthyIsSet(true);
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.message = iprot.readString();
        struct.setMessageIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.error = new ArrayList<HealthCheckResultError>(_list13.size);
          for (int _i14 = 0; _i14 < _list13.size; ++_i14)
          {
            HealthCheckResultError _elem15;
            _elem15 = new HealthCheckResultError();
            _elem15.read(iprot);
            struct.error.add(_elem15);
          }
        }
        struct.setErrorIsSet(true);
      }
    }
  }

}

