/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.fourtwosix.codahale.metrics.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MetricRegistry implements org.apache.thrift.TBase<MetricRegistry, MetricRegistry._Fields>, java.io.Serializable, Cloneable, Comparable<MetricRegistry> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("MetricRegistry");

  private static final org.apache.thrift.protocol.TField GAUGES_FIELD_DESC = new org.apache.thrift.protocol.TField("gauges", org.apache.thrift.protocol.TType.MAP, (short)1);
  private static final org.apache.thrift.protocol.TField COUNTERS_FIELD_DESC = new org.apache.thrift.protocol.TField("counters", org.apache.thrift.protocol.TType.MAP, (short)2);
  private static final org.apache.thrift.protocol.TField HISTOGRAMS_FIELD_DESC = new org.apache.thrift.protocol.TField("histograms", org.apache.thrift.protocol.TType.MAP, (short)3);
  private static final org.apache.thrift.protocol.TField METERS_FIELD_DESC = new org.apache.thrift.protocol.TField("meters", org.apache.thrift.protocol.TType.MAP, (short)4);
  private static final org.apache.thrift.protocol.TField TIMERS_FIELD_DESC = new org.apache.thrift.protocol.TField("timers", org.apache.thrift.protocol.TType.MAP, (short)5);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new MetricRegistryStandardSchemeFactory());
    schemes.put(TupleScheme.class, new MetricRegistryTupleSchemeFactory());
  }

  public Map<String,Gauge> gauges; // required
  public Map<String,Counter> counters; // required
  public Map<String,HistogramSnapshot> histograms; // required
  public Map<String,Meter> meters; // required
  public Map<String,TimerSnapshot> timers; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GAUGES((short)1, "gauges"),
    COUNTERS((short)2, "counters"),
    HISTOGRAMS((short)3, "histograms"),
    METERS((short)4, "meters"),
    TIMERS((short)5, "timers");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GAUGES
          return GAUGES;
        case 2: // COUNTERS
          return COUNTERS;
        case 3: // HISTOGRAMS
          return HISTOGRAMS;
        case 4: // METERS
          return METERS;
        case 5: // TIMERS
          return TIMERS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GAUGES, new org.apache.thrift.meta_data.FieldMetaData("gauges", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Gauge.class))));
    tmpMap.put(_Fields.COUNTERS, new org.apache.thrift.meta_data.FieldMetaData("counters", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Counter.class))));
    tmpMap.put(_Fields.HISTOGRAMS, new org.apache.thrift.meta_data.FieldMetaData("histograms", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, HistogramSnapshot.class))));
    tmpMap.put(_Fields.METERS, new org.apache.thrift.meta_data.FieldMetaData("meters", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Meter.class))));
    tmpMap.put(_Fields.TIMERS, new org.apache.thrift.meta_data.FieldMetaData("timers", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, TimerSnapshot.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(MetricRegistry.class, metaDataMap);
  }

  public MetricRegistry() {
  }

  public MetricRegistry(
    Map<String,Gauge> gauges,
    Map<String,Counter> counters,
    Map<String,HistogramSnapshot> histograms,
    Map<String,Meter> meters,
    Map<String,TimerSnapshot> timers)
  {
    this();
    this.gauges = gauges;
    this.counters = counters;
    this.histograms = histograms;
    this.meters = meters;
    this.timers = timers;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public MetricRegistry(MetricRegistry other) {
    if (other.isSetGauges()) {
      Map<String,Gauge> __this__gauges = new HashMap<String,Gauge>(other.gauges.size());
      for (Map.Entry<String, Gauge> other_element : other.gauges.entrySet()) {

        String other_element_key = other_element.getKey();
        Gauge other_element_value = other_element.getValue();

        String __this__gauges_copy_key = other_element_key;

        Gauge __this__gauges_copy_value = new Gauge(other_element_value);

        __this__gauges.put(__this__gauges_copy_key, __this__gauges_copy_value);
      }
      this.gauges = __this__gauges;
    }
    if (other.isSetCounters()) {
      Map<String,Counter> __this__counters = new HashMap<String,Counter>(other.counters.size());
      for (Map.Entry<String, Counter> other_element : other.counters.entrySet()) {

        String other_element_key = other_element.getKey();
        Counter other_element_value = other_element.getValue();

        String __this__counters_copy_key = other_element_key;

        Counter __this__counters_copy_value = new Counter(other_element_value);

        __this__counters.put(__this__counters_copy_key, __this__counters_copy_value);
      }
      this.counters = __this__counters;
    }
    if (other.isSetHistograms()) {
      Map<String,HistogramSnapshot> __this__histograms = new HashMap<String,HistogramSnapshot>(other.histograms.size());
      for (Map.Entry<String, HistogramSnapshot> other_element : other.histograms.entrySet()) {

        String other_element_key = other_element.getKey();
        HistogramSnapshot other_element_value = other_element.getValue();

        String __this__histograms_copy_key = other_element_key;

        HistogramSnapshot __this__histograms_copy_value = new HistogramSnapshot(other_element_value);

        __this__histograms.put(__this__histograms_copy_key, __this__histograms_copy_value);
      }
      this.histograms = __this__histograms;
    }
    if (other.isSetMeters()) {
      Map<String,Meter> __this__meters = new HashMap<String,Meter>(other.meters.size());
      for (Map.Entry<String, Meter> other_element : other.meters.entrySet()) {

        String other_element_key = other_element.getKey();
        Meter other_element_value = other_element.getValue();

        String __this__meters_copy_key = other_element_key;

        Meter __this__meters_copy_value = new Meter(other_element_value);

        __this__meters.put(__this__meters_copy_key, __this__meters_copy_value);
      }
      this.meters = __this__meters;
    }
    if (other.isSetTimers()) {
      Map<String,TimerSnapshot> __this__timers = new HashMap<String,TimerSnapshot>(other.timers.size());
      for (Map.Entry<String, TimerSnapshot> other_element : other.timers.entrySet()) {

        String other_element_key = other_element.getKey();
        TimerSnapshot other_element_value = other_element.getValue();

        String __this__timers_copy_key = other_element_key;

        TimerSnapshot __this__timers_copy_value = new TimerSnapshot(other_element_value);

        __this__timers.put(__this__timers_copy_key, __this__timers_copy_value);
      }
      this.timers = __this__timers;
    }
  }

  public MetricRegistry deepCopy() {
    return new MetricRegistry(this);
  }

  @Override
  public void clear() {
    this.gauges = null;
    this.counters = null;
    this.histograms = null;
    this.meters = null;
    this.timers = null;
  }

  public int getGaugesSize() {
    return (this.gauges == null) ? 0 : this.gauges.size();
  }

  public void putToGauges(String key, Gauge val) {
    if (this.gauges == null) {
      this.gauges = new HashMap<String,Gauge>();
    }
    this.gauges.put(key, val);
  }

  public Map<String,Gauge> getGauges() {
    return this.gauges;
  }

  public MetricRegistry setGauges(Map<String,Gauge> gauges) {
    this.gauges = gauges;
    return this;
  }

  public void unsetGauges() {
    this.gauges = null;
  }

  /** Returns true if field gauges is set (has been assigned a value) and false otherwise */
  public boolean isSetGauges() {
    return this.gauges != null;
  }

  public void setGaugesIsSet(boolean value) {
    if (!value) {
      this.gauges = null;
    }
  }

  public int getCountersSize() {
    return (this.counters == null) ? 0 : this.counters.size();
  }

  public void putToCounters(String key, Counter val) {
    if (this.counters == null) {
      this.counters = new HashMap<String,Counter>();
    }
    this.counters.put(key, val);
  }

  public Map<String,Counter> getCounters() {
    return this.counters;
  }

  public MetricRegistry setCounters(Map<String,Counter> counters) {
    this.counters = counters;
    return this;
  }

  public void unsetCounters() {
    this.counters = null;
  }

  /** Returns true if field counters is set (has been assigned a value) and false otherwise */
  public boolean isSetCounters() {
    return this.counters != null;
  }

  public void setCountersIsSet(boolean value) {
    if (!value) {
      this.counters = null;
    }
  }

  public int getHistogramsSize() {
    return (this.histograms == null) ? 0 : this.histograms.size();
  }

  public void putToHistograms(String key, HistogramSnapshot val) {
    if (this.histograms == null) {
      this.histograms = new HashMap<String,HistogramSnapshot>();
    }
    this.histograms.put(key, val);
  }

  public Map<String,HistogramSnapshot> getHistograms() {
    return this.histograms;
  }

  public MetricRegistry setHistograms(Map<String,HistogramSnapshot> histograms) {
    this.histograms = histograms;
    return this;
  }

  public void unsetHistograms() {
    this.histograms = null;
  }

  /** Returns true if field histograms is set (has been assigned a value) and false otherwise */
  public boolean isSetHistograms() {
    return this.histograms != null;
  }

  public void setHistogramsIsSet(boolean value) {
    if (!value) {
      this.histograms = null;
    }
  }

  public int getMetersSize() {
    return (this.meters == null) ? 0 : this.meters.size();
  }

  public void putToMeters(String key, Meter val) {
    if (this.meters == null) {
      this.meters = new HashMap<String,Meter>();
    }
    this.meters.put(key, val);
  }

  public Map<String,Meter> getMeters() {
    return this.meters;
  }

  public MetricRegistry setMeters(Map<String,Meter> meters) {
    this.meters = meters;
    return this;
  }

  public void unsetMeters() {
    this.meters = null;
  }

  /** Returns true if field meters is set (has been assigned a value) and false otherwise */
  public boolean isSetMeters() {
    return this.meters != null;
  }

  public void setMetersIsSet(boolean value) {
    if (!value) {
      this.meters = null;
    }
  }

  public int getTimersSize() {
    return (this.timers == null) ? 0 : this.timers.size();
  }

  public void putToTimers(String key, TimerSnapshot val) {
    if (this.timers == null) {
      this.timers = new HashMap<String,TimerSnapshot>();
    }
    this.timers.put(key, val);
  }

  public Map<String,TimerSnapshot> getTimers() {
    return this.timers;
  }

  public MetricRegistry setTimers(Map<String,TimerSnapshot> timers) {
    this.timers = timers;
    return this;
  }

  public void unsetTimers() {
    this.timers = null;
  }

  /** Returns true if field timers is set (has been assigned a value) and false otherwise */
  public boolean isSetTimers() {
    return this.timers != null;
  }

  public void setTimersIsSet(boolean value) {
    if (!value) {
      this.timers = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case GAUGES:
      if (value == null) {
        unsetGauges();
      } else {
        setGauges((Map<String,Gauge>)value);
      }
      break;

    case COUNTERS:
      if (value == null) {
        unsetCounters();
      } else {
        setCounters((Map<String,Counter>)value);
      }
      break;

    case HISTOGRAMS:
      if (value == null) {
        unsetHistograms();
      } else {
        setHistograms((Map<String,HistogramSnapshot>)value);
      }
      break;

    case METERS:
      if (value == null) {
        unsetMeters();
      } else {
        setMeters((Map<String,Meter>)value);
      }
      break;

    case TIMERS:
      if (value == null) {
        unsetTimers();
      } else {
        setTimers((Map<String,TimerSnapshot>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case GAUGES:
      return getGauges();

    case COUNTERS:
      return getCounters();

    case HISTOGRAMS:
      return getHistograms();

    case METERS:
      return getMeters();

    case TIMERS:
      return getTimers();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case GAUGES:
      return isSetGauges();
    case COUNTERS:
      return isSetCounters();
    case HISTOGRAMS:
      return isSetHistograms();
    case METERS:
      return isSetMeters();
    case TIMERS:
      return isSetTimers();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof MetricRegistry)
      return this.equals((MetricRegistry)that);
    return false;
  }

  public boolean equals(MetricRegistry that) {
    if (that == null)
      return false;

    boolean this_present_gauges = true && this.isSetGauges();
    boolean that_present_gauges = true && that.isSetGauges();
    if (this_present_gauges || that_present_gauges) {
      if (!(this_present_gauges && that_present_gauges))
        return false;
      if (!this.gauges.equals(that.gauges))
        return false;
    }

    boolean this_present_counters = true && this.isSetCounters();
    boolean that_present_counters = true && that.isSetCounters();
    if (this_present_counters || that_present_counters) {
      if (!(this_present_counters && that_present_counters))
        return false;
      if (!this.counters.equals(that.counters))
        return false;
    }

    boolean this_present_histograms = true && this.isSetHistograms();
    boolean that_present_histograms = true && that.isSetHistograms();
    if (this_present_histograms || that_present_histograms) {
      if (!(this_present_histograms && that_present_histograms))
        return false;
      if (!this.histograms.equals(that.histograms))
        return false;
    }

    boolean this_present_meters = true && this.isSetMeters();
    boolean that_present_meters = true && that.isSetMeters();
    if (this_present_meters || that_present_meters) {
      if (!(this_present_meters && that_present_meters))
        return false;
      if (!this.meters.equals(that.meters))
        return false;
    }

    boolean this_present_timers = true && this.isSetTimers();
    boolean that_present_timers = true && that.isSetTimers();
    if (this_present_timers || that_present_timers) {
      if (!(this_present_timers && that_present_timers))
        return false;
      if (!this.timers.equals(that.timers))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(MetricRegistry other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetGauges()).compareTo(other.isSetGauges());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGauges()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.gauges, other.gauges);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCounters()).compareTo(other.isSetCounters());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCounters()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.counters, other.counters);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetHistograms()).compareTo(other.isSetHistograms());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetHistograms()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.histograms, other.histograms);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMeters()).compareTo(other.isSetMeters());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMeters()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.meters, other.meters);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTimers()).compareTo(other.isSetTimers());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimers()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.timers, other.timers);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("MetricRegistry(");
    boolean first = true;

    sb.append("gauges:");
    if (this.gauges == null) {
      sb.append("null");
    } else {
      sb.append(this.gauges);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("counters:");
    if (this.counters == null) {
      sb.append("null");
    } else {
      sb.append(this.counters);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("histograms:");
    if (this.histograms == null) {
      sb.append("null");
    } else {
      sb.append(this.histograms);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("meters:");
    if (this.meters == null) {
      sb.append("null");
    } else {
      sb.append(this.meters);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("timers:");
    if (this.timers == null) {
      sb.append("null");
    } else {
      sb.append(this.timers);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (gauges == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'gauges' was not present! Struct: " + toString());
    }
    if (counters == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'counters' was not present! Struct: " + toString());
    }
    if (histograms == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'histograms' was not present! Struct: " + toString());
    }
    if (meters == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'meters' was not present! Struct: " + toString());
    }
    if (timers == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'timers' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class MetricRegistryStandardSchemeFactory implements SchemeFactory {
    public MetricRegistryStandardScheme getScheme() {
      return new MetricRegistryStandardScheme();
    }
  }

  private static class MetricRegistryStandardScheme extends StandardScheme<MetricRegistry> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, MetricRegistry struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GAUGES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map16 = iprot.readMapBegin();
                struct.gauges = new HashMap<String,Gauge>(2*_map16.size);
                for (int _i17 = 0; _i17 < _map16.size; ++_i17)
                {
                  String _key18;
                  Gauge _val19;
                  _key18 = iprot.readString();
                  _val19 = new Gauge();
                  _val19.read(iprot);
                  struct.gauges.put(_key18, _val19);
                }
                iprot.readMapEnd();
              }
              struct.setGaugesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // COUNTERS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map20 = iprot.readMapBegin();
                struct.counters = new HashMap<String,Counter>(2*_map20.size);
                for (int _i21 = 0; _i21 < _map20.size; ++_i21)
                {
                  String _key22;
                  Counter _val23;
                  _key22 = iprot.readString();
                  _val23 = new Counter();
                  _val23.read(iprot);
                  struct.counters.put(_key22, _val23);
                }
                iprot.readMapEnd();
              }
              struct.setCountersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // HISTOGRAMS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map24 = iprot.readMapBegin();
                struct.histograms = new HashMap<String,HistogramSnapshot>(2*_map24.size);
                for (int _i25 = 0; _i25 < _map24.size; ++_i25)
                {
                  String _key26;
                  HistogramSnapshot _val27;
                  _key26 = iprot.readString();
                  _val27 = new HistogramSnapshot();
                  _val27.read(iprot);
                  struct.histograms.put(_key26, _val27);
                }
                iprot.readMapEnd();
              }
              struct.setHistogramsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // METERS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map28 = iprot.readMapBegin();
                struct.meters = new HashMap<String,Meter>(2*_map28.size);
                for (int _i29 = 0; _i29 < _map28.size; ++_i29)
                {
                  String _key30;
                  Meter _val31;
                  _key30 = iprot.readString();
                  _val31 = new Meter();
                  _val31.read(iprot);
                  struct.meters.put(_key30, _val31);
                }
                iprot.readMapEnd();
              }
              struct.setMetersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TIMERS
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map32 = iprot.readMapBegin();
                struct.timers = new HashMap<String,TimerSnapshot>(2*_map32.size);
                for (int _i33 = 0; _i33 < _map32.size; ++_i33)
                {
                  String _key34;
                  TimerSnapshot _val35;
                  _key34 = iprot.readString();
                  _val35 = new TimerSnapshot();
                  _val35.read(iprot);
                  struct.timers.put(_key34, _val35);
                }
                iprot.readMapEnd();
              }
              struct.setTimersIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, MetricRegistry struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.gauges != null) {
        oprot.writeFieldBegin(GAUGES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.gauges.size()));
          for (Map.Entry<String, Gauge> _iter36 : struct.gauges.entrySet())
          {
            oprot.writeString(_iter36.getKey());
            _iter36.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.counters != null) {
        oprot.writeFieldBegin(COUNTERS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.counters.size()));
          for (Map.Entry<String, Counter> _iter37 : struct.counters.entrySet())
          {
            oprot.writeString(_iter37.getKey());
            _iter37.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.histograms != null) {
        oprot.writeFieldBegin(HISTOGRAMS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.histograms.size()));
          for (Map.Entry<String, HistogramSnapshot> _iter38 : struct.histograms.entrySet())
          {
            oprot.writeString(_iter38.getKey());
            _iter38.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.meters != null) {
        oprot.writeFieldBegin(METERS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.meters.size()));
          for (Map.Entry<String, Meter> _iter39 : struct.meters.entrySet())
          {
            oprot.writeString(_iter39.getKey());
            _iter39.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.timers != null) {
        oprot.writeFieldBegin(TIMERS_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, struct.timers.size()));
          for (Map.Entry<String, TimerSnapshot> _iter40 : struct.timers.entrySet())
          {
            oprot.writeString(_iter40.getKey());
            _iter40.getValue().write(oprot);
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class MetricRegistryTupleSchemeFactory implements SchemeFactory {
    public MetricRegistryTupleScheme getScheme() {
      return new MetricRegistryTupleScheme();
    }
  }

  private static class MetricRegistryTupleScheme extends TupleScheme<MetricRegistry> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, MetricRegistry struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      {
        oprot.writeI32(struct.gauges.size());
        for (Map.Entry<String, Gauge> _iter41 : struct.gauges.entrySet())
        {
          oprot.writeString(_iter41.getKey());
          _iter41.getValue().write(oprot);
        }
      }
      {
        oprot.writeI32(struct.counters.size());
        for (Map.Entry<String, Counter> _iter42 : struct.counters.entrySet())
        {
          oprot.writeString(_iter42.getKey());
          _iter42.getValue().write(oprot);
        }
      }
      {
        oprot.writeI32(struct.histograms.size());
        for (Map.Entry<String, HistogramSnapshot> _iter43 : struct.histograms.entrySet())
        {
          oprot.writeString(_iter43.getKey());
          _iter43.getValue().write(oprot);
        }
      }
      {
        oprot.writeI32(struct.meters.size());
        for (Map.Entry<String, Meter> _iter44 : struct.meters.entrySet())
        {
          oprot.writeString(_iter44.getKey());
          _iter44.getValue().write(oprot);
        }
      }
      {
        oprot.writeI32(struct.timers.size());
        for (Map.Entry<String, TimerSnapshot> _iter45 : struct.timers.entrySet())
        {
          oprot.writeString(_iter45.getKey());
          _iter45.getValue().write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, MetricRegistry struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      {
        org.apache.thrift.protocol.TMap _map46 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.gauges = new HashMap<String,Gauge>(2*_map46.size);
        for (int _i47 = 0; _i47 < _map46.size; ++_i47)
        {
          String _key48;
          Gauge _val49;
          _key48 = iprot.readString();
          _val49 = new Gauge();
          _val49.read(iprot);
          struct.gauges.put(_key48, _val49);
        }
      }
      struct.setGaugesIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map50 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.counters = new HashMap<String,Counter>(2*_map50.size);
        for (int _i51 = 0; _i51 < _map50.size; ++_i51)
        {
          String _key52;
          Counter _val53;
          _key52 = iprot.readString();
          _val53 = new Counter();
          _val53.read(iprot);
          struct.counters.put(_key52, _val53);
        }
      }
      struct.setCountersIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map54 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.histograms = new HashMap<String,HistogramSnapshot>(2*_map54.size);
        for (int _i55 = 0; _i55 < _map54.size; ++_i55)
        {
          String _key56;
          HistogramSnapshot _val57;
          _key56 = iprot.readString();
          _val57 = new HistogramSnapshot();
          _val57.read(iprot);
          struct.histograms.put(_key56, _val57);
        }
      }
      struct.setHistogramsIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map58 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.meters = new HashMap<String,Meter>(2*_map58.size);
        for (int _i59 = 0; _i59 < _map58.size; ++_i59)
        {
          String _key60;
          Meter _val61;
          _key60 = iprot.readString();
          _val61 = new Meter();
          _val61.read(iprot);
          struct.meters.put(_key60, _val61);
        }
      }
      struct.setMetersIsSet(true);
      {
        org.apache.thrift.protocol.TMap _map62 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.timers = new HashMap<String,TimerSnapshot>(2*_map62.size);
        for (int _i63 = 0; _i63 < _map62.size; ++_i63)
        {
          String _key64;
          TimerSnapshot _val65;
          _key64 = iprot.readString();
          _val65 = new TimerSnapshot();
          _val65.read(iprot);
          struct.timers.put(_key64, _val65);
        }
      }
      struct.setTimersIsSet(true);
    }
  }

}

